# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [21]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [22]:
# Create a 1-dimensional NumPy array using np.array()
One = np.array([0,5,5,3,1,7])

# Create a 2-dimensional NumPy array using np.array()
Two = np.array([[0,1,2,3],[2,4,6,8]])

# Create a 3-dimensional Numpy array using np.array()
Three = np.array([
        [[0,1,2,3],[2,4,6,8]],[[1,3,5,7],[5,6,7,8]]
                ])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [23]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(One.shape)
print(One.ndim)
print(One.size)
print(One.dtype)
print(type(One))

(6,)
1
6
int32
<class 'numpy.ndarray'>


In [24]:
# Attributes of 2-dimensional array
print(Two.shape)
print(Two.ndim)
print(Two.size)
print(Two.dtype)
print(type(Two))

(2, 4)
2
8
int32
<class 'numpy.ndarray'>


In [25]:
# Attributes of 3-dimensional array
print(Three.shape)
print(Three.ndim)
print(Three.size)
print(Three.dtype)
print(type(Three))

(2, 2, 4)
3
16
int32
<class 'numpy.ndarray'>


In [26]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(Two)
df

0  1  2  3
0  0  1  2  3
1  2  4  6  8

In [27]:
# Create an array of shape (10, 2) with only ones
x = np.ones( (10,2) )
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
# Create an array of shape (7, 2, 3) of only zeros
y = np.zeros( (7, 2, 3) )
y

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [29]:
# Create an array within a range of 0 and 100 with step 3
z = np.arange(0,100,3)
z

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [30]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_array_1 = np.random.randint(0, 10, size=(7, 2))
rand_array_1

array([[9, 3],
       [7, 6],
       [8, 7],
       [4, 1],
       [4, 7],
       [9, 8],
       [8, 0]])

In [31]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_array_2 = np.random.random(size=(3,5))
rand_array_2

array([[0.01563641, 0.42340148, 0.39488152, 0.29348817, 0.01407982],
       [0.1988424 , 0.71134195, 0.79017554, 0.60595997, 0.92630088],
       [0.65107703, 0.91495968, 0.85003858, 0.44945067, 0.09541012]])

In [32]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_array_3 = np.random.randint(0, 10, size=(4, 6))
rand_array_3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens? The numbers dont change

Are the numbers in the array different or the same? Why do think this is? The same, as the seed number is fixed 42

In [33]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_array_4 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
unique_values = np.unique(rand_array_4)
unique_values

array([1, 2, 3, 4, 5, 7, 9])

In [34]:
# Find the 0'th index of the latest array you created
rand_array_4[0]

array([9, 1, 3, 7, 4, 9, 3])

In [35]:
# Get the first 2 rows of latest array you created
rand_array_4[0:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [36]:
# Get the first 2 values of the first 2 rows of the latest array
print(rand_array_4[0][0:2])
print(rand_array_4[1][0:2])

[9 1]
[5 3]


In [37]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_array_5 = np.random.randint(1, 10, size=(3, 5))
print(rand_array_5)

rand_array_6 = np.ones( (3, 5) )
print(rand_array_6)

[[7 8 3 1 4]
 [2 8 4 2 6]
 [6 4 6 2 2]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
# Add the two arrays together
add_array = rand_array_5 + rand_array_6
add_array

array([[8., 9., 4., 2., 5.],
       [3., 9., 5., 3., 7.],
       [7., 5., 7., 3., 3.]])

In [39]:
# Create another array of ones of shape (5, 3)
rand_array_7 = np.ones( (5, 3) )
rand_array_7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# Try add the array of ones and the other most recent array together
add_array = rand_array_7 + add_array

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?  because they are not the same shape

How would you fix it?  by reshaping one of them

In [41]:
# Create another array of ones of shape (3, 5)
rand_array_8 = np.ones( (3, 5) )

In [42]:
# Subtract the new array of ones from the other most recent array
print(rand_array_5 - rand_array_8)

[[6. 7. 2. 0. 3.]
 [1. 7. 3. 1. 5.]
 [5. 3. 5. 1. 1.]]


In [43]:
# Multiply the ones array with the latest array
print(rand_array_8 * rand_array_5)

[[7. 8. 3. 1. 4.]
 [2. 8. 4. 2. 6.]
 [6. 4. 6. 2. 2.]]


In [44]:
# Take the latest array to the power of 2 using '**'
print(rand_array_5 ** 2)

[[49 64  9  1 16]
 [ 4 64 16  4 36]
 [36 16 36  4  4]]


In [45]:
# Do the same thing with np.square()
print( np.square(rand_array_5) )

[[49 64  9  1 16]
 [ 4 64 16  4 36]
 [36 16 36  4  4]]


In [46]:
# Find the mean of the latest array using np.mean()
np.mean(rand_array_5)

4.333333333333333

In [47]:
# Find the maximum of the latest array using np.max()
np.max(rand_array_5)

8

In [48]:
# Find the minimum of the latest array using np.min()
np.min(rand_array_5)

1

In [49]:
# Find the standard deviation of the latest array
np.std(rand_array_5)

2.270584848790187

In [50]:
# Find the variance of the latest array
np.var(rand_array_5)

5.155555555555556

In [51]:
# Reshape the latest array to (3, 5, 1)
np.reshape( rand_array_5 , newshape=(3, 5, 1) )

array([[[7],
        [8],
        [3],
        [1],
        [4]],

       [[2],
        [8],
        [4],
        [2],
        [6]],

       [[6],
        [4],
        [6],
        [2],
        [2]]])

In [52]:
# Transpose the latest array
np.transpose(rand_array_5)

array([[7, 2, 6],
       [8, 8, 4],
       [3, 4, 6],
       [1, 2, 2],
       [4, 6, 2]])

What does the transpose do?  swap the dimensions

In [53]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand_array_9 = np.random.randint(0,10, size=(3, 3))
rand_array_10 = np.random.randint(0,10, size=(3, 2))

In [54]:
# Perform a dot product on the two newest arrays you created
print( np.dot(rand_array_9,rand_array_10) )

[[ 87 161]
 [106 174]
 [ 36  76]]


In [55]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand_array_11 = np.random.randint(0,10, size=(4, 3))
rand_array_12 = np.random.randint(0,10, size=(4, 3))

In [56]:
# Perform a dot product on the two newest arrays you created
print( np.dot(rand_array_11,rand_array_12) )

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?  by transposing one of them

In [57]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
rand_array_11 = np.transpose(rand_array_11)
print( np.dot(rand_array_11,rand_array_12) )

[[ 40  80  50]
 [ 95 140 102]
 [147 168  91]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [58]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand_array_13 = np.random.randint(0,10, size=(3, 3))
rand_array_14 = np.random.randint(0,10, size=(3, 3))
print(rand_array_13)
print(rand_array_14)

[[7 4 2]
 [7 5 2]
 [0 2 4]]
[[2 0 4]
 [9 6 6]
 [8 9 9]]


In [59]:
# Compare the two arrays with '>'
print(rand_array_13 > rand_array_14)

[[ True  True False]
 [False False False]
 [False False False]]


What happens when you compare the arrays with `>`?  it returns an array with true if bigger and false when not

In [60]:
# Compare the two arrays with '>='
print(rand_array_13 >= rand_array_14)

[[ True  True False]
 [False False False]
 [False False False]]


In [61]:
# Find which elements of the first array are greater than 7
print(rand_array_13 > 7)

[[False False False]
 [False False False]
 [False False False]]


In [62]:
# Which parts of each array are equal? (try using '==')
print(rand_array_13 == rand_array_14)

[[False False False]
 [False False False]
 [False False False]]


In [63]:
# Sort one of the arrays you just created in ascending order
rand_array_13.sort()
rand_array_13

array([[2, 4, 7],
       [2, 5, 7],
       [0, 2, 4]])

In [64]:
# Sort the indexes of one of the arrays you just created
rand_array_13.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [65]:
# Find the index with the maximum value in one of the arrays you've created
print( rand_array_14.argmax() )

3


In [66]:
# Find the index with the minimum value in one of the arrays you've created
print( rand_array_14.argmin() )

1


In [67]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
print( rand_array_14.argmax(axis=1) )

[2 0 1]


In [68]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
print( rand_array_14.argmin(axis=0) )

[0 0 0]


In [69]:
# Create an array of normally distributed random numbers

# Mean of the distribution
mu = 0
# Standard deviation of the distribution
sigma = 1
rand_array = np.random.normal(mu, sigma, 20)
rand_array

array([-1.38071702, -0.28080629, -0.05981726,  0.96117377,  1.79428084,
        0.58068954,  0.29765045, -1.02811577, -1.41859646,  0.19033698,
        0.13575383,  0.60808966,  0.70498131,  0.36092338, -1.46696789,
        0.89262947, -0.10525713, -0.95534644, -0.41476463, -1.39874088])

In [70]:
# Create an array with 10 evenly spaced numbers between 1 and 100
rand_array = np.linspace(1,100,10)
rand_array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.